-- 用户表
CREATE TABLE IF NOT EXISTS  QQ_USER (
    UID  INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    USER_NICK_NAME  VARCHAR (64) NOT NULL  COMMENT '用户昵称',
    USER_NAME  VARCHAR (64) default NULL  COMMENT '用户真实姓名',
    SEX  tinyint DEFAULT 1  COMMENT '用户性别0:保密,1:男,2:女',
    BIRTHDAY  DATE DEFAULT NULL  COMMENT '生日',
    CONSTELLATION  tinyint DEFAULT NULL  COMMENT '星座',
    ADDRESS  VARCHAR(60) DEFAULT NULL  COMMENT '现居住地',
    HOMETOWN  VARCHAR(60) DEFAULT NULL  COMMENT '故乡',
    PICTURE  VARCHAR(100) DEFAULT NULL  COMMENT '头像',
    SIGNATURE   VARCHAR(100) DEFAULT NULL  COMMENT '个性说明',
    PHONE   VARCHAR(20) NOT NULL  COMMENT '手机号',
    EMAI   VARCHAR(50) NOT NULL  COMMENT '电子邮箱',
    PASSWORD   VARCHAR(80) NOT NULL  COMMENT '密码',
    USER_STATUS  tinyint DEFAULT 1  COMMENT '用户状态:0:注销,1正常,2:锁定',
    CREATE_TIME datetime NOT NULL COMMENT '添加时间',
    UPDATE_TIME datetime NOT NULL COMMENT '修改时间',
    PRIMARY KEY (UID),
    UNIQUE KEY USER_PHONE_INDEX (PHONE),
    UNIQUE KEY USER_EMAI_INDEX (EMAI),
    KEY USER_NICK_NAME_INDEX (USER_NICK_NAME)
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COMMENT'用户表';


-- 好友分组表
CREATE TABLE IF NOT EXISTS  QQ_FRIENDS_TYPE (
    TID  INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    TYPE_NAME  VARCHAR (64) NOT NULL  COMMENT '分组名称',
    CREATE_TIME datetime NOT NULL COMMENT '添加时间',
    PRIMARY KEY (TID)
    ) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COMMENT'好友分组表';

-- 好友分组表关系表
CREATE TABLE IF NOT EXISTS  QQ_FRIENDS_TYPE_RELATION (
    RID  INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    USER_ID  INT(11)  NOT NULL  COMMENT '用户ID',
    TID  INT(11)  NOT NULL  COMMENT '分组ID',
    CREATE_TIME datetime NOT NULL COMMENT '添加时间',
    PRIMARY KEY (RID),
    KEY TYPE_RELATION_USER_ID(USER_ID),
    KEY TYPE_RELATION_TID(TID)
    ) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COMMENT'好友分组关系表';

-- 好友表
CREATE TABLE IF NOT EXISTS  QQ_FRIENDS (
    FID  INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    FRIEND_NICK_NAME  VARCHAR (64) DEFAULT NULL  COMMENT '好友备注',
    USER_ID  INT(11)  NOT NULL  COMMENT '用户ID',
    FRIEND_USER_ID  VARCHAR (64) DEFAULT NULL  COMMENT '好友ID',
    RID  INT(11) DEFAULT NULL  COMMENT '好友分组ID',
    FRIEND_TYPE tinyint DEFAULT 1  COMMENT '好友类型：1好友,2群聊',
    MESSAGE_REMINDING  tinyint DEFAULT 1  COMMENT '消息提醒类型',
    CREATE_TIME datetime NOT NULL COMMENT '添加时间',
    UPDATE_TIME datetime NOT NULL COMMENT '修改时间',
    PRIMARY KEY (FID),
     KEY FRIENDS_USER_ID_INDEX (USER_ID),
     KEY FRIEND_USER_ID_INDEX (FRIEND_USER_ID),
     KEY FRIEND_RID_INDEX (RID)
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COMMENT'好友表';



-- 消息列表
CREATE TABLE IF NOT EXISTS  QQ_FRIEND_SESSION (
    SID  INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    USER_ID INT(11) NOT NULL  COMMENT '用户ID',
    FRIEND_USER_ID INT(11) NOT NULL  COMMENT '好友ID',
    SESSION_TYPE  tinyint DEFAULT 0  COMMENT '是否群组:0:不是,1是',
    SESSION_STATUS tinyint DEFAULT 0 COMMENT '会话状态:0:删除,1显示,2隐藏,3 置顶',
    CREATE_TIME datetime NOT NULL COMMENT '添加时间',
    UPDATE_TIME datetime NOT NULL COMMENT '修改时间',
    PRIMARY KEY (SID),
    KEY SESSION_USER_ID (USER_ID),
    KEY SESSION_FRIEND_USER_ID (FRIEND_USER_ID)
    ) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COMMENT'消息列表';

-- 会话消息关联表
CREATE TABLE IF NOT EXISTS  QQ_FRIEND_SESSION_CHATTING_RELATION (
    CRID  INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    CID INT(11) NOT NULL  COMMENT '消息ID',
    SID INT(11) NOT NULL  COMMENT '会话ID',
    IS_LAST  tinyint DEFAULT 0  COMMENT '是否最后1条:0,不是最后1条，1是最后1条',
    IS_READ  tinyint DEFAULT 0  COMMENT '是否未读:0未读，1已读,2撤回',
    PRIMARY KEY (CRID),
    KEY RELATION_CID (CID),
    KEY RELATION_SID (SID)
    ) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COMMENT'会话消息关联表';

-- 消息记录表
CREATE TABLE IF NOT EXISTS  QQ_FRIEND_CHATTING_RECORDS (
    CID  INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    TO_ID INT(11) NOT NULL  COMMENT '消息接受人',
    FROM_ID INT(11) NOT NULL  COMMENT '消息发起人',
    CHATTING_TEXT  text DEFAULT NULL  COMMENT '消息内容',
    CREATE_TIME  bigint NOT NULL  COMMENT '消息发送时间时间戳',
    CREATE_DATE  dateTime NOT NULL  COMMENT '消息发送时间',
    MESSAGE_TYPE  tinyint DEFAULT 1  COMMENT '消息类型:1文本消息,2:表情,3:文件消息',
    MESSAGE_EXE  VARCHAR(300) DEFAULT NULL  COMMENT '消息扩展数据',
    MESSAGE_GROUP  tinyint DEFAULT 1  COMMENT '是否群聊消息:1好友消息,2群聊消息',
    MESSAGE_AT  tinyint DEFAULT 0  COMMENT '0无艾特,1艾特',
    MESSAGE_AT_ID INT(11) DEFAULT -1  COMMENT '-1无艾特，0艾特全部，其他艾特具体的人',
    PRIMARY KEY (CID),
    KEY RECORDS_TO_ID (TO_ID),
    KEY RECORDS_FROM_ID (FROM_ID),
    KEY RECORDS_CREATE_TIME (CREATE_TIME),
    KEY RECORDS_CREATE_DATE (CREATE_DATE)
    ) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COMMENT'消息记录表';


-- 群组表
CREATE TABLE IF NOT EXISTS  QQ_FRIEND_GROUP (
    GID  INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    GROUP_NAME INT(11) NOT NULL  COMMENT '群名称',
    GROUP_DESC VARCHAR(300) NOT NULL  COMMENT '群介绍',
    GROUP_PHOTO  VARCHAR(300) DEFAULT NULL  COMMENT '群头像',
    GROUP_CREATE_USER INT(11) NOT  NULL  COMMENT '群创建人',
    GROUP_CREATE_DATE  dateTime NOT NULL  COMMENT '创建时间',
    PRIMARY KEY (GID)
    ) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COMMENT'群组表';

-- 群组成员表
CREATE TABLE IF NOT EXISTS  QQ_FRIEND_GROUP_USER (
    GUID  INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    USER_ID INT(11) NOT NULL  COMMENT '成员ID',
    GID INT(11) NOT NULL  COMMENT '群ID',
    GROUP_USER_GRADE tinyint DEFAULT 0  COMMENT '0:普通成员，1:群主，2:群管理员',
    MY_GROUP_NAME VARCHAR(64) DEFAULT NULL  COMMENT '我在群备注',
    ADD_GROUP_DATE  dateTime NOT NULL  COMMENT '创建时间',
    PRIMARY KEY (GUID),
    KEY GROUP_USER_ID (GID),
    KEY GROUP_ID (USER_ID)
    ) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COMMENT'群组成员表';

-- 业务消息记录表
CREATE TABLE IF NOT EXISTS  QQ_BUSINESS_MESSAGE (
    MESSAGE_ID  INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    USER_ID INT(11) NOT NULL  COMMENT '成员ID',
    FROM_ID INT(11) NOT NULL  COMMENT '发送方ID',
    GID  INT(11) DEFAULT 0  COMMENT '群组ID',
    BUSINESS_TYPE tinyint NOT NULL  COMMENT '2:添加好友',
    MESSAGE  VARCHAR(500) NOT NULL  COMMENT '消息内容',
    MESSAGE_EXE TEXT DEFAULT NULL COMMENT '扩展消息内容',
    IS_READ tinyint DEFAULT 0 COMMENT '是否读取:0:未读，1已读',
    CREATE_TIME datetime NOT NULL COMMENT '添加时间',
    UPDATE_TIME datetime NOT NULL COMMENT '修改时间',
    PRIMARY KEY (MESSAGE_ID),
    KEY BUSINESS_USER_ID (USER_ID),
    KEY BUSINESS_FROM_ID (FROM_ID)
    ) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COMMENT'业务消息记录表';