-- 用户表
CREATE TABLE IF NOT EXISTS  QQ_USER (
    UID  INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    USER_NICK_NAME  VARCHAR (64) NOT NULL  COMMENT '用户昵称',
    USER_NAME  VARCHAR (64) default NULL  COMMENT '用户真实姓名',
    SEX  tinyint default 1  COMMENT '用户性别0:未知,1:男,2:女',
    BIRTHDAY  date default NULL  COMMENT '生日',
    CONSTELLATION  tinyint default NULL  COMMENT '星座',
    ADDRESS  VARCHAR(60) default NULL  COMMENT '现居住地',
    HOMETOWN  VARCHAR(60) default NULL  COMMENT '故乡',
    PICTURE  VARCHAR(100) default NULL  COMMENT '头像',
    SIGNATURE   VARCHAR(100) default NULL  COMMENT '个性说明',
    PHONE   VARCHAR(20) NOT NULL  COMMENT '手机号',
    EMAI   VARCHAR(50) NOT NULL  COMMENT '电子邮箱',
    PASSWORD   VARCHAR(80) NOT NULL  COMMENT '密码',
    USER_STATUS  tinyint default 1  COMMENT '用户状态:',
    PRIMARY KEY (UID),
    UNION KEY EMAI_INDEX (EMAI),
    UNION KEY PHONE_INDEX (PHONE),
    KEY USER_NICK_NAME_INDEX (USER_NICK_NAME)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT'用户表';

-- 好友表
CREATE TABLE IF NOT EXISTS  QQ_FRIENDS (
    FID  INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    FRIEND_NICK_NAME  VARCHAR (64) NOT NULL  COMMENT '好友备注',
    USER_ID  VARCHAR (64) default NULL  COMMENT '用户ID',
    FRIEND_USER_ID  VARCHAR (64) default NULL  COMMENT '好友ID',
    FRIEND_GROUP  tinyint default 1  COMMENT '好友分组',
    FRIEND_TYPE tinyint default 1  COMMENT '好友类型：1好友,2群聊',
    MY_GROUP_NAME VARCHAR(64) default NULL  COMMENT '我在群备注',
    MESSAGE_REMINDING  tinyint default 1  COMMENT '消息提醒类型',
    CREATE_TIME datetime NOT NULL COMMENT '添加时间',
    UPDATE_TIME datetime NOT NULL COMMENT '修改时间',
    PRIMARY KEY (FID),
     KEY FRIENDS_USER_ID_INDEX (USER_ID),
     KEY FRIEND_USER_ID_INDEX (FRIEND_USER_ID)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT'好友表';

-- 聊天记录表
CREATE TABLE IF NOT EXISTS  QQ_FRIEND_CHATTING_RECORDS (
    CID  INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    TO_ID INT(11) NOT NULL  COMMENT '消息接受人',
    FROM_ID INT(11) NOT NULL  COMMENT '消息发起人',
    CHATTING_TEXT  text default NULL  COMMENT '消息内容',
    CREATE_TIME  bigint NOT NULL  COMMENT '消息发送时间时间戳',
    CREATE_DATE  dateTime NOT NULL  COMMENT '消息发送时间',
    MESSAGE_TYPE  tinyint default 1  COMMENT '消息类型',
    MESSAGE_EXE  varchar(300) default NULL  COMMENT '消息扩展数据',
    MESSAGE_GROUP  tinyint default 1  COMMENT '是否群聊消息:1好友消息,2群聊消息',
    MESSAGE_AT  tinyint default 0  COMMENT '0无艾特,1艾特',
    MESSAGE_AT_ID INT(11) default -1  COMMENT '-1无艾特，0艾特全部，其他艾特具体的人',
    PRIMARY KEY (FID),
    KEY RECORDS_TO_ID (TO_ID),
    KEY RECORDS_FROM_ID (FROM_ID),
    KEY RECORDS_CREATE_TIME (CREATE_TIME),
    KEY RECORDS_CREATE_TIME (CREATE_DATE)
    ) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT'消息记录表';


-- 群组表
CREATE TABLE IF NOT EXISTS  QQ_FRIEND_GROUP (
    GID  INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    GROUP_NAME INT(11) NOT NULL  COMMENT '群名称',
    GROUP_DESC varchar(300) NOT NULL  COMMENT '群介绍',
    GROUP_photo  varchar(300) default NULL  COMMENT '群头像',
    GROUP_CREATE_user INT(11) NOT  NULL  COMMENT '群创建人',
    GROUP_CREATE_DATE  dateTime NOT NULL  COMMENT '创建时间',
    PRIMARY KEY (GID)
    ) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT'群组表';

-- 群组成员表
CREATE TABLE IF NOT EXISTS  QQ_FRIEND_GROUP_USER (
    GID  INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    USER_ID INT(11) NOT NULL  COMMENT '成员ID',
    GROUP_USER_GRADE tinyint default 0  COMMENT '0:普通成员，1:群主，2:群管理员',
    GROUP_PHOTO  varchar(300) default NULL  COMMENT '群头像',
    GROUP_CREATE_USER INT(11) NOT  NULL  COMMENT '群创建人',
    GROUP_CREATE_DATE  dateTime NOT NULL  COMMENT '创建时间',
    PRIMARY KEY (GID),
    KEY GROUP_USER_ID (USER_ID)
    ) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT'群组成员表';