server:
  port: 8001
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        password: nacos
        username: nacos
        namespace: 9e5e194a-ff8a-42f3-8b77-d7831880fc6b
        group: book
    gateway:
      discovery:
        locator:
          enabled: false #自动路由，由服务名去找对应的服务，自带负载均衡，默认关闭
      routes: # 路由规则
        - id: order-server
          uri: lb://order-service
          predicates:
            - Path=/order-server/**
          filters:
            - StripPrefix=1
