server:
  port: 8010
spring:
  application:
    name: book-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: 9e5e194a-ff8a-42f3-8b77-d7831880fc6b
        group: book